# Generated by Django 4.2.13 on 2024-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0004_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
