# Generated by Django 4.2.13 on 2024-06-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='mark.CartItem', to='mark.product'),
        ),
    ]
